# Generated by Django 3.1.6 on 2021-02-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(max_length=100)),
                ('keywords', models.TextField()),
                ('content', models.TextField()),
                ('extracted_from', models.CharField(max_length=100)),
                ('extracted_by', models.CharField(max_length=100)),
                ('extracted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
